//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class attend
    {
        public int id { get; set; }
        public string teachName { get; set; }
        public string groupname { get; set; }
        public string date { get; set; }
        public string theme { get; set; }
        public string notes { get; set; }
    }
}
