//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class member
    {
        public int id { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public string telnum { get; set; }
        public string teachname { get; set; }
        public string groupname { get; set; }
    }
}
